### ISSUE TITLE
battery not charging

### ISSUE THREAD

**Issue by gled-rs** [makerdiary/python-keyboard#27]
Hi guys, posting here, seems more active than the community forums :)

I have a m.60 keyboard, and I bought a battery with a JST 3 pin connector ( https://www.ebay.com/itm/173602816497 )

Voltage reads 3.82V, both on the multi-meter and in the firmware on p0_02 ( using battery_level ), so for a lipo, rough estimate around 50% charge.

I have checked the thermistor resistance is a proper 10k, NTC is working properly, test points on the pcb show also a 9.9k ohms using the multi-meter.

Plugging into multiple different usb ports ( usb-a and usb-c ), I know those ports are able to charge my phone, p0_03 stays True all the time, so no charging happening ( and I don't see either the voltage rising ). 

Another issue, plugging an external battery on the usb port instead of going to the computer, the board freezes, keyboard seems to stay connected to bluetooth, but no more typing possible ( I tried to use the switch bt key to make sure the keyboard was not trying to send to usb ). But that is secondary, main issue is the inability to charge.

Is there something special I missed to be able to charge that battery by any chance ?

**Comment by gled-rs** [comment]
I tried today a second battery and using a 10k resistor on the test contact points as outlined here: https://github.com/makerdiary/python-keyboard/issues/4#issuecomment-753388065. Everything checks out using a multimeter.

Still no charging happening, I am on "Adafruit CircuitPython 6.0.0-alpha.1-110-ga7a4315e5 on 2021-01-17" firmware.

Is it possible I have a faulty board or is the firmware somehow preventing to charge ?

**Comment by mehalter** [comment]
I have been having the exact same issue with the JST 3 pin connector battery (original poster of #4) that I have attached to mine. Please post an update if you figure out a solution. I have done a lot of debugging with the battery and can't for the life of me get it to charge. The battery I originally purchased from Ebay I did notice had the JST connector wired up incorrectly and after rearranging the pins I got it to function on the battery power without freezing, but haven't been able to get it to charge and have resorted to just using the device as a wired keyboard (which is luckily fine for my main use case). Hopefully this issue can get resolved because having it battery powered would be a very nice perk!

**Comment by gled-rs** [comment]
At this point we need @xiongyihui to help us I think.

I tried to identify the charger chip, it seems like cdu ti 018 would be a ti bq24075, but I am having trouble identifying the pinout wiring, seems like it does not match the doc I find... Not too much bandwidth in that subject unfortunately... 

To rule out battery issue, I can confirm the battery I am using can charge without issues on a mcp73833 charger.

**Comment by caizelin** [comment]
@gled-rs I have noticed that the battery you found has the incorrect polarity. The incorrent polarity will damage the charger ic. Please double-check the polarity of your battery. Here is the corrent connector that M60 should use (3p JST 1.25plug):

![image](https://user-images.githubusercontent.com/37929607/107311515-74792800-6ac9-11eb-901a-73b346fcbdba.png)

**Comment by gled-rs** [comment]
I do have the proper polarity, I corrected that before the first plug, since it was obvious from the pcb.. board is powered properly when on battery, just not charging...   Voltage is being read properly too.

I take it that you can charge on yours ?

> @gled-rs I have noticed that the battery you found has the incorrect polarity. The incorrent polarity will damage the charger ic. Please double-check the polarity of your battery. Here is the corrent connector that M60 should use (3p JST 1.25plug):
> 
> ![image](https://user-images.githubusercontent.com/37929607/107311515-74792800-6ac9-11eb-901a-73b346fcbdba.png)

**Comment by mehalter** [comment]
bump @xiongyihui , have you had any luck @gled-rs ?

**Comment by gled-rs** [comment]
> bump @xiongyihui , have you had any luck @gled-rs ?

@mehalter 

Unfortunately not. 

Discussion went a bit further here https://community.makerdiary.com/t/m60-battery-not-charging/370/10 but no solution in sight.

I tested two batteries so far, both of which were able to power other projects and charge perfectly fine, so the batteries I am using are not the issue. Voltage reading in the firmware is correct too, verified that. Also checked that thermistor is properly working too.

As it stands, it's either that there's a faulty batch of boards that were shipped ( I now know of 3 boards not charging and 2 working ), or that there's something else I can't figure out. 

I do not have the time at the moment to investigate further, I just wish MD would reply to my support request for a board exchange to check if this is a faulty board problem though...

The only solution I would suggest at that point, without MD input or exchange of the faulty board, is to forget about using the builtin charger and use a small lipo charger in the case ( you can find some small ones that fit in cases on Adafruit or Mouser, and solder the output on the m60 to power it ), that would expose a second usb port used only for charging, which is kinda stupid but would do the job to have this m60 wireless. 

I haven't done that yet tbh, but considering that or switching to another keyboard that actually can charge, which is sad because I really like the m60, it's a very unfortunate flaw...

**Comment by mehalter** [comment]
@gled-rs thanks for the information. I'll start following the discussion thread there as well. Hopefully MD reaches back out to you. I'll contact them too about a possible faulty board and see if I have any luck. Please let me know if anything comes out of future investigations you do and I'll do the same!

**Comment by nitz** [comment]
I'm having the exact same issue. My board was one of the original runs, were y'alls early too? I'd been using it wired til just recently I finally bought a battery. The battery I got had the polarity wrong, so I had to swap the pins. Seemed like it worked fine, and I used it on that charge for a few weeks. Was dead just the other day and I plugged it in and left it for a few hours. Still doesn't want to charge at all. Here's a photo of it plugged into a 45W USB C PD charger, through my USB-C Volt/ammeter. Doesn't like to pull more than just about ~30mA, no matter what I try to get it to do. Guess it's back to wired only for a while!

![image](https://user-images.githubusercontent.com/602691/111056795-eb4e6b80-844f-11eb-80ca-328e02779006.png)

**Comment by mehalter** [comment]
Yeah, I pre-ordered mine Early and it was in a very early batch. Hopefully @xiongyihui can follow up and see if these seemingly defective boards could be an production issue or suggest a potential fix

**Comment by nitz** [comment]
Interesting. Reading the thread @gled-rs linked, I noticed @caizelin mentioning that reverse polarity could have damaged the charging IC. There's certainly a chance I did that to mine, as I certainly had to swap the pins because they weren't right, but I really can't remember.

Through a bit of clever needle usage and an old lipo charger, I rigged it up to charge the 3 pin battery I have. After leaving it on there for an hour or so, I checked the voltage with the multimeter, and it was over 3.7, so I hooked it back to the keyboard and it worked just fine. Still not charging when plugged in, but the battery definitely works fine, so I'm definitely looking towards the charger IC now.

**Comment by danieljarolim** [comment]
I had a similar charging problem. Keyboard worked fine from battery but I wasn't seeing a voltage increase when plugged in except for regular voltage spikes. Keyboard was also showing battery had only a few % charge. Turned out battery was wired + - sensor, and keyboard is wired + sensor - so I was discharging through the 10k thermistor. I couldn't find battery connector wiring anywhere in the keyboard docs.

**Comment by mehalter** [comment]
@danieljarolim were you able to resolve this issue with a new batter that was wired differently? If so, could you also provide a link to a battery that you know is working? I would love to fix this with my keyboard. Thanks for the information!

**Comment by danieljarolim** [comment]
I just rewired the connector on the battery by switching the ground and thermistor sensor wires to fix the problem. You can insert a pin from the wire side into the plug to release the metal connector from these types of plugs and reconnect in new location. 

I bough this battery locally but you won't want it, it's too thick for most cases. https://ecocell.com.au/product/lipo-1000-603450-3w/  In the description: "The yellow wire is connected to an onboard 10kΩ NTC Temperature Sensor." so thermistor is the last wire. The battery comes with an incorrect 2mm plug so I also bought a jst 1.25 3 pin connector with wires and that was also wired red black yellow so I assumed that was the standard. A multimeter shows the keyboard plug is wired differently to that: + thermistor - .

I also tried with a 2 wire battery and connected a 10k resistor between ground on the battery and middle pin of plug, and that also works.

**Comment by gled-rs** [comment]
I do believe that some keyboards just have a faulty charger, or no working chargers at all.

I tested extensively two boards so far, with the proper batteries wiring, no reverse polarity happened, and none worked.

It seems like a lottery at this point.

I won't be able to provide more testing though, I retired that board and switched to a proper working keyboard, and the other person I was testing with has done the same.
